// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6XO9iXvwcU2vNktbLjXScQ_QDfUy9Xac',
    appId: '1:278549662505:web:9b3c537adb998684b3c538',
    messagingSenderId: '278549662505',
    projectId: 'story-king-94d54',
    authDomain: 'story-king-94d54.firebaseapp.com',
    storageBucket: 'story-king-94d54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItrwHXq_YNrq_b4rvnWF6W2OtUiWNNwE',
    appId: '1:278549662505:android:e4fceb17f83e2502b3c538',
    messagingSenderId: '278549662505',
    projectId: 'story-king-94d54',
    storageBucket: 'story-king-94d54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSf5T9qqIXzp8pigHxuIJj6KOh7ilh_RI',
    appId: '1:278549662505:ios:2409db82417a3b8ab3c538',
    messagingSenderId: '278549662505',
    projectId: 'story-king-94d54',
    storageBucket: 'story-king-94d54.firebasestorage.app',
    iosBundleId: 'com.example.androidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSf5T9qqIXzp8pigHxuIJj6KOh7ilh_RI',
    appId: '1:278549662505:ios:2409db82417a3b8ab3c538',
    messagingSenderId: '278549662505',
    projectId: 'story-king-94d54',
    storageBucket: 'story-king-94d54.firebasestorage.app',
    iosBundleId: 'com.example.androidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6XO9iXvwcU2vNktbLjXScQ_QDfUy9Xac',
    appId: '1:278549662505:web:b51539c48262e99bb3c538',
    messagingSenderId: '278549662505',
    projectId: 'story-king-94d54',
    authDomain: 'story-king-94d54.firebaseapp.com',
    storageBucket: 'story-king-94d54.firebasestorage.app',
  );
}
